# KL Recycling ML Training Configuration
# Comprehensive settings for scrap metal detection and weight prediction

# =============================================================================
# DATASET CONFIGURATION
# =============================================================================
dataset:
  name: "kl_recycling_scrap_dataset_v2"
  version: "2.0.0"
  materials:
    - steel
    - aluminum
    - copper
    - brass
    - mixed_scrap

  image_format: "jpg"
  label_format: "pascal_voc"  # pascal_voc, coco, yolo

  # Quality thresholds
  min_resolution: 640  # Minimum image width/height
  max_resolution: 4096
  required_reference_objects: true

  # Training data split
  train_split: 0.7
  val_split: 0.2
  test_split: 0.1

  # Data augmentation
  augmentation:
    flip_horizontal: true
    flip_vertical: false
    rotation_range: [-15, 15]
    brightness_range: [0.8, 1.2]
    contrast_range: [0.8, 1.2]
    saturation_range: [0.8, 1.2]
    hue_range: [-10, 10]
    blur_prob: 0.1
    noise_prob: 0.05

# =============================================================================
# MODEL ARCHITECTURES
# =============================================================================
models:
  object_detection:
    yolo_v8:
      size: "medium"  # nano, small, medium, large, xlarge
      pretrained: true
      freeze_backbone: false
      input_size: 640
      batch_size: 16
      epochs: 100
      learning_rate: 0.001
      weight_decay: 0.0005
      momentum: 0.937

    efficient_det:
      model_name: "efficientdet-d4"
      pretrained: true
      input_size: 896
      batch_size: 8
      epochs: 50
      learning_rate: 0.01

  weight_prediction:
    cnn_regressor:
      architecture: "resnet50"  # resnet50, vgg16, efficientnet
      input_size: 224
      batch_size: 32
      epochs: 50
      learning_rate: 0.001
      dropout_rate: 0.3

    ensemble_model:
      use_object_detection: true
      use_material_classifier: true
      use_reference_calibration: true

# =============================================================================
# TRAINING PARAMETERS
# =============================================================================
training:
  # Hardware
  device: "auto"  # auto, cuda, cpu
  mixed_precision: true
  gradient_checkpointing: false

  # Optimization
  optimizer: "adam"  # adam, sgd, adamw
  scheduler: "cosine"  # cosine, linear, step
  warmup_steps: 100

  # Regularization
  label_smoothing: 0.1
  augment_strong: true

  # Early stopping
  patience: 10
  min_delta: 0.001

  # Logging & Checkpointing
  log_every: 10  # steps
  save_every: 5   # epochs
  eval_every: 2   # epochs

# =============================================================================
# EVALUATION METRICS
# =============================================================================
evaluation:
  # Object Detection
  object_detection_metrics:
    - mAP_50
    - mAP_75
    - mAP_50_95
    - precision
    - recall

  # Weight Prediction
  weight_prediction_metrics:
    - mean_absolute_error
    - mean_squared_error
    - r2_score
    - mean_absolute_percentage_error

  # Custom Metrics
  custom_metrics:
    - material_classification_accuracy
    - weight_estimation_within_5_percent
    - weight_estimation_within_10_percent
    - reference_object_detection_rate

# =============================================================================
# DEPLOYMENT & OPTIMIZATION
# =============================================================================
deployment:
  target_platforms:
    - android
    - ios

  optimization:
    quantization: "dynamic_range"  # none, dynamic_range, full_integer, float16
    input_size: 320  # Optimized for mobile
    max_detections: 100
    score_threshold: 0.3
    iou_threshold: 0.45

  performance_targets:
    inference_time_target: 50  # ms on mobile GPU
    model_size_target: 15      # MB
    memory_usage_target: 200   # MB

# =============================================================================
# MATERIAL PROPERTIES & WEIGHT CALCULATIONS
# =============================================================================
materials:
  steel:
    density_kg_m3: 7850
    common_forms: ["sheet", "pipe", "beam", "scrap"]
    weight_multipliers:
      sheet: 1.0
      pipe: 0.8
      beam: 1.2
      scrap: 0.7

  aluminum:
    density_kg_m3: 2710
    common_forms: ["can", "sheet", "foil", "extrusion"]
    weight_multipliers:
      can: 0.9
      sheet: 1.0
      foil: 0.3
      extrusion: 1.4

  copper:
    density_kg_m3: 8960
    common_forms: ["wire", "pipe", "sheet", "scrap"]
    weight_multipliers:
      wire: 0.6
      pipe: 1.0
      sheet: 1.3
      scrap: 0.8

  brass:
    density_kg_m3: 8500
    common_forms: ["fixture", "pipe", "casting", "scrap"]
    weight_multipliers:
      fixture: 1.1
      pipe: 1.0
      casting: 1.5
      scrap: 0.7

# =============================================================================
# EXPERIMENT TRACKING & MONITORING
# =============================================================================
monitoring:
  wandb:
    project: "kl_recycling_ml"
    entity: "kl_recycling"
    log_model: true
    log_code: true

  mlflow:
    experiment_name: "scrap_metal_detection"
    tracking_uri: "./mlruns"

  tensorboard:
    log_dir: "./logs"
    histogram_freq: 1
    profile_batch: 2

# =============================================================================
# DATA QUALITY & VALIDATION
# =============================================================================
quality_control:
  image_quality_checks:
    brightness_threshold: [0.2, 0.8]     # Min/Max normalized brightness
    blur_threshold: 0.7                   # Laplacian variance
    contrast_threshold: 0.3               # RMS contrast
    saturation_threshold: 0.1             # Color saturation

  label_quality_checks:
    min_box_size: 32                      # Minimum box dimension
    max_aspect_ratio: 5.0                 # Max width/height ratio
    iou_overlap_threshold: 0.8            # For duplicate detection
    reference_object_required: true       # Must have reference for calibration

  weight_validation:
    min_weight_pounds: 0.1
    max_weight_pounds: 1000
    outlier_detection: true
    outlier_threshold: 3.0  # Standard deviations
